set backspace=indent,eol,start
set clipboard=unnamed
set guitablabel=%M%t
set helplang=en
set langmenu=none
set listchars=tab:\ \
set mouse=a
set printexpr=system('open\ -a\ Preview\ '.v:fname_in)\ +\ v:shell_error
set termencoding=utf-8
